# Generated by Django 2.0.4 on 2018-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('img', models.FileField(default='unknown', upload_to='../img/')),
            ],
        ),
    ]
